name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{ secrets.DB_PASS }}
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        ports:
           - 5432:5432
    steps:
    - uses: actions/checkout@v3
    - uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_FIREBASE_CREDENTIAL: ${{ secrets.FIREBASE_CREDENTIAL }}
        envkey_DB_NAME: ${{ secrets.DB_NAME }}
        envkey_DB_PASS: ${{ secrets.DB_PASS }}
        envkey_DB_USER: ${{ secrets.DB_USER }}
        envkey_DB_HOST: ${{ secrets.DB_HOST }}
        envkey_DB_PORT: 5432
        envkey_PORT: ${{ secrets.PORT }}
        directory: ./
        file_name: .test.env
        fail_on_empty: false

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

      

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
